#!/bin/bash

pwd=$(pwd)
if [[ "$pwd" != */server ]]; then
    echo "Please run this inside the server folder of the repo"
    exit 1
fi

echo "Stopping the server..."
pkill gunicorn
tmux kill-session -t escout 2> /dev/null

echo "Starting the server..."
tmux new-session -s escout -d "tmux set remain-on-exit on && cd $PWD && gunicorn -c scripts/gunicorn.py.ini 'app:app'"
